# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: engeo-frontend-deployment
#   namespace: "2401075"
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: engeo-connect
#   template:
#     metadata:
#       labels:
#         app: engeo-connect
#     spec:
#       imagePullSecrets:
#         - name: nexus-secret
#       containers:
#         - name: engeo-connect
#           image: 127.0.0.1:30085/2401075_ngo/ngo:v1
#           imagePullPolicy: Always
#           ports:
#             - containerPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: engeo-frontend-deployment
  namespace: "2401075"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engeo-connect
  template:
    metadata:
      labels:
        app: engeo-connect
    spec:
      containers:
        - name: engeo-connect
          image: host.docker.internal:30085/2401075_ngo/ngo:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80

