apiVersion: apps/v1
kind: Deployment
metadata:
  name: engeo-frontend-deployment
  namespace: "2401075"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engeo-connect
  template:
    metadata:
      labels:
        app: engeo-connect
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        -name: nexus-secret 
      containers:
        - name: engeo-connect
          image: 120.0.0.1:30085/2401075_ngo/ngo:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: engeo-frontend-service
  namespace: "2401075"
spec:
  type: NodePort
  selector:
    app: engeo-connect
  ports:
    - protocol: TCP
      port: 80        # Cluster-internal
      targetPort: 80  # Pod container port
      nodePort: 31086 # Host accessible port (FREE)


