apiVersion: apps/v1
kind: Deployment
metadata:
  name: engeo-frontend-deployment
  namespace: "2401075"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engeo-connect
  template:
    metadata:
      labels:
        app: engeo-connect
    spec:
      automountServiceAccountToken: false     # ✔ FIX: Disable automounting (SonarQube security issue)
      containers:
        - name: engeo-connect
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401075_ngo/ngo:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:                         # ✔ FIX: Add CPU, Memory, Storage requests & limits
            requests:
              cpu: "100m"                    # ✔ CPU request
              memory: "256Mi"                # ✔ Memory request
              ephemeral-storage: "256Mi"     # ✔ Storage request
            limits:
              cpu: "500m"                    # ✔ CPU limit
              memory: "512Mi"                # ✔ Memory limit
