# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: engeo-frontend-service
# #   namespace: "2401075"
# # spec:
# #   type: NodePort
# #   selector:
# #     app: engeo-connect
# #   ports:
# #     - protocol: TCP
# #       port: 80
# #       targetPort: 80
# #       nodePort: 31075


# apiVersion: v1
# kind: Service
# metadata:
#   name: engeo-frontend-service
#   namespace: "2401075"
# spec:
#   type: ClusterIP
#   selector:
#     app: engeo-connect
#   ports:
#     - port: 80
#       targetPort: 8080


apiVersion: v1
kind: Service
metadata:
  name: engeo-frontend-service
  namespace: "2401075"
spec:
  type: NodePort
  selector:
    app: engeo-connect
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31075