# apiVersion: v1
# kind: Service
# metadata:
#   name: engeo-frontend-deployment
#   namespace: "2401075"
# spec:
#   selector:
#     app: engeo-connect
#   ports:
#     - protocol: TCP
#       port: 80 # Internal cluster port
#       targetPort: 80 # Pod container port
#       nodePort: 31075 # Host accessible port (FREE PORT)
#   type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: engeo-frontend-service
  namespace: "2401075"
spec:
  type: NodePort
  selector:
    app: engeo-connect
  ports:
    - port: 80
      targetPort: 80
